n_steps: &n_steps 15
val_n_steps: *n_steps
env_name: &env_name maze2d_large_diverse
compile_model: False
root_path: &root_path /scratch/wz1232/HWM_PLDM

base_lr: 0.017632900482959527
data:
  normalize: true
  dataset_type: DatasetType.D4RL
  num_workers: 10
  prefetch_factor: 4
  normalizer_hardset: true
  d4rl_config:
    env_name: *env_name
    random_actions: false
    img_size: 98
    alpha: 0.6
    batch_size: 128
    beta: 0.4
    crop_length: null
    images_path: /scratch/wz1232/data/maze2d_large_diverse_25maps/images.npy
    path: ${root_path}/pldm_envs/diverse_maze/datasets/maze2d_large_diverse_25maps/data.p
    location_only: false
    num_workers: 10
    prioritized: false
    quick_debug: false
    n_steps: *n_steps
    seed: 0
    stack_states: 1
    train: true
    val_fraction: 0.2
epochs: 3
eval_at_beginning: false
eval_during_training: false
eval_every_n_epochs: 2
eval_mpcs: 20
eval_only: false
hjepa:
  l1_n_steps: *n_steps
  train_l1: true
  freeze_l1: false
  disable_l2: true
  level1:
    backbone:
      arch: menet6
      backbone_subclass: d4rl_a
      backbone_mlp: null
      backbone_width_factor: 2
      input_dim: 4
      channels: 3
      late_proprio_cfg:
        encoder_arch: 'id_expand'
        ignore: false
        fuse: true
    predictor:
      residual: true
      action_encoder_arch: 'id'
      predictor_arch: conv2
      predictor_subclass: d4rl_b_p
      rnn_converter_arch: ''
      rnn_layers: 1
      rnn_state_dim: 512
      z_dim: 0
      z_min_std: 0.1
    encode_only: false
    use_z_goal: false
    action_dim: 2
  step_skip: 4
load_checkpoint_path: null
load_l1_only: false
objectives_l1:
  idm:
    action_dim: 2
    coeff: 4.810550706458433
    arch: 'conv'
    use_pred: false
    arch_subclass: a
  objectives:
  - ObjectiveType.VICRegObs
  - ObjectiveType.IDM
  - ObjectiveType.PredictionProprio
  probe:
    coeff: 1
    arch_subclass: 'b'
  vicreg_obs:
    adjust_cov: true
    cov_chunk_size: null
    cov_coeff: 17.8664279184067
    cov_coeff_t: 0
    cov_per_feature: false
    projector: id
    random_projector: false
    sim_coeff: 1
    std_coeff: 29.409481669124336
    std_coeff_t: 2.9199
    sim_coeff_t: 0
  prediction_proprio:
    global_coeff: 2.416154262252218
optimizer_type: Adam
output_dir: maze2d_large_diverse
output_root: ${root_path}/checkpoint/maze2d_large_diverse
eval_cfg:
  disable_planning: false
  env_name: *env_name
  log_heatmap: false
  eval_l1: true
  probing:
    l1_depth: *n_steps
    train_images_path: /scratch/wz1232/data/maze2d_large_diverse_probe/images.npy
    train_path: ${root_path}/pldm_envs/diverse_maze/datasets/maze2d_large_diverse_probe/data.p
    val_images_path: /scratch/wz1232/data/maze2d_large_diverse_probe/images.npy
    val_path: ${root_path}/pldm_envs/diverse_maze/datasets/maze2d_large_diverse_probe/data.p
    probe_targets: 'locations'
    diff_targets: 'obs_component'
    locations:
      arch: 'conv'
      subclass: 'c'
      extract_field: 'obs_component'
    l2_probe_targets: 'locations'
    probe_mpc: false
    probe_wall: false
    probe_proprio: true
    probe_encoder: false
    probe_preds: true
    epochs: 5
    epochs_enc: 5
    epochs_latent: 5
    full_finetune: false
    lr: 0.0032
    max_samples: 2000000
    max_samples_enc: 2000000
    schedule: Cosine
    visualize_probing: true
    load_prober: false
  d4rl_planning:
    n_envs: 85
    n_envs_batch_size: 20
    n_steps: 192
    levels: "easy,medium,hard"
    easy:
      n_steps: 500
      n_envs: 40
      max_plan_length: 150
      plot_every: 10
      min_block_radius: 4
      max_block_radius: 9999
      override_config: true
      set_start_target_path: "${root_path}/pldm_envs/diverse_maze/datasets/maze2d_large_diverse_probe/starts_targets_5_8.pt"
      level1:
        mppi:
          num_samples: 125
    medium:
      n_steps: 500
      n_envs: 40
      max_plan_length: 200
      plot_every: 10
      min_block_radius: 4
      max_block_radius: 9999
      override_config: true
      set_start_target_path: "${root_path}/pldm_envs/diverse_maze/datasets/maze2d_large_diverse_probe/starts_targets_9_12.pt"
      level1:
        mppi:
          num_samples: 250
    hard:
      n_steps: 500
      n_envs: 40
      max_plan_length: 250
      plot_every: 10
      min_block_radius: 4
      max_block_radius: 9999
      override_config: true
      set_start_target_path: "${root_path}/pldm_envs/diverse_maze/datasets/maze2d_large_diverse_probe/starts_targets_13_16.pt"
      level1:
        mppi:
          num_samples: 250
    log_pred_dist_every: 9999999
    plot_every: 16
    action_repeat: 4
    action_repeat_mode: 'id'
    img_size: 98
    replan_every: 4
    image_obs: true
    stack_states: 1
    data_path: "${root_path}/pldm_envs/diverse_maze/datasets/maze2d_large_diverse_probe/"
    level1:
      planner_type: PlannerType.MPPI
      min_step: 0
      max_step: 1
      max_plan_length: 128
      sgd:
        action_change_reg: 0
        l2_reg: 0
        lr: 0.03
        n_iters: 200
      mppi:
        noise_sigma: 5
        num_samples: 125
        lambda_: 0.0025
    #d4rl specific
    position_only: true
quick_debug: false
run_group: test
run_name: test
run_project: HJEPA-maze-v3
save_every_n_epochs: 1
seed: 246
wandb: true
